Chores/update use of env vars #160877304
SFDigitalServices/sf-dahlia-lap pull request #120
Opened 2018-10-01 17:17 UTC by callaghanc

2018-10-01 23:24 UTC, akegan requested changes
Can you update the instructions for the e2e tests that say you need to have the env vars actually in your environment?

2018-10-01 23:24 UTC, akegan commented on .git-hooks/pre_commit/scan_for_env_vars.rb
> +module Overcommit
do you want help QAing this?

2018-10-01 23:27 UTC, callaghanc commented on .git-hooks/pre_commit/scan_for_env_vars.rb
> +module Overcommit
would be great if any/all who are doing PR review can do QA as part of review - so, please actually try out everything in this PR locally and see if it works for you!

2018-10-01 23:39 UTC, callaghanc commented
@akegan Updated e2e test section in README.

2018-10-02 00:01 UTC, akegan commented
OK
- E2E tests worked for me with unset env vars
- Overcommit caught when I was using a value of an env var. The only headache it might cause is that I have yellow acres set as the default listing ID right now in https://github.com/Exygy/sf-dahlia-lap/blame/master/spec/javascript/support/puppeteer/consts.js#L2. We might run into trouble with those.

![image](https://user-images.githubusercontent.com/11825994/46322005-7e0a3100-c59b-11e8-8e1f-0a53cfe2f580.png)

2018-10-02 00:02 UTC, akegan approved these changes

2018-10-02 00:06 UTC, callaghanc commented
@akegan For the default listing/application ID in the consts file, it seems that if we have that as a default, a person would not need that same value in their local .env? Is that what you were referring to?

2018-10-02 15:59 UTC, akegan commented
yep. I was thinking the same thing too but I just wanted to flag it.

2018-10-02 17:27 UTC, callaghanc commented
yep makes sense. in general it will be something we'll have to consider if we in the future need to add an env variable with a common value - for example, if we need to add a flag env var whose value is just true/false. in that case, we'll need to add a way to exclude certain variables from this check. but we can handle that when that case arises.

2018-10-02 18:09 UTC, merged