Features/lease up export #154064904
SFDigitalServices/sf-dahlia-lap pull request #156
Opened 2018-11-07 15:44 UTC by akegan

https://www.pivotaltracker.com/story/show/154064904

2018-11-07 15:45 UTC, akegan commented on config/routes.rb
> +  get 'reports/:id' => redirect { |params| "#{ENV['SALESFORCE_INSTANCE_URL']}/#{params[:id]}?csv=1" }
@chrisdolendo @callaghanc I am trying to do the redirect here but I don't know if we have access to whether or not a user is an admin here and this needs to be ENV['COMMUNITY_LOGIN_URL'] if they're not an admin

2018-11-07 22:48 UTC, callaghanc commented
@akegan I changed the setting of the `SALESFORCE_BASE_URL` global to use a more standard format for interpolating Ruby into an embedded Javascript Slim section. That now works in both dev and prod. Now I'm interested in why the syntax you had before worked in development at all! I'm going to move onto other things I have to do today, but you may want to look into that a bit for your own edification, and I'll return to this tmrw to follow up as well.

2018-11-08 09:41 UTC, akegan commented
Thanks! that's what I was going to try next 😄

2018-11-08 11:06 UTC, akegan commented on spec/vcr/listings/applications_controller/index.yml
> -      - Mon, 22 Oct 2018 19:10:14 GMT
VCR cassettes had to be updated to include the Report__id

2018-11-08 21:45 UTC, callaghanc commented
@akegan I tried this out on the review app and I wasn't able to download the report while logged into the review app as an admin user. When I clicked on the Export link, a new tab opened with a Salesforce login page, asking me to log in. Could you look into this? It's likely something on the Salesforce side.

Somewhat relatedly, perhaps we should think of adding testing around whether users of different permission levels can access the reports, since that's really been the sticky question all along with this feature.

2018-11-08 23:05 UTC, callaghanc requested changes
I'm putting a changes requested review on this to indicate that a review was done and the result was there are some outstanding questions around this functionality. Don't actually have any specific code change requests.

2018-11-13 11:58 UTC, akegan commented
I was able to reproduce your issue @callaghanc. It looks like I had been separately logged into test.salesforce.com in my browser when I was testing. It looks like this is an issue with salesforce sessions transferring over. I'll check with vertiba to see if this can be easily resolved.

If not, we might have to keep the login step for MOHCD admins if they need to download a report this way

2018-11-15 17:07 UTC, akegan commented
@callaghanc see chat on the ticket. We are not going to implement a fix for the bug you found (although it's a good one!) pls review/accept ASAP so we can get it over to product testing

2018-11-15 18:16 UTC, callaghanc approved these changes

2018-11-16 22:56 UTC, akegan commented
did another quick spot check on this and it's still good to go! merging now

2018-11-16 22:56 UTC, merged