Bug - Open House Inconsistencies 166098541
SFDigitalServices/sf-dahlia-lap pull request #261
Opened 2019-05-31 05:36 UTC by LoganArnett

This PR covers ticket [#166098541](https://www.pivotaltracker.com/story/show/166098541) regarding open house information not being parsed correctly.

It appears that this was due to the helper function forcing the fields to lowercase so even though we saw a date it was incorrect as the field was pulling from `date` instead of `Date` and the times were attempting to pull from `start_time` and `end_time` instead of `Start_Time` and `End_Time`.

2019-06-04 19:16 UTC, akegan commented on spec/javascript/components/listing/__snapshots__/ListingPage.test.js.snap
> -            Legal Disclaimers
@LoganArnett do you know why so many lines were removed in this snapshot?

2019-06-04 19:18 UTC, akegan requested changes
Update. Looks like snapshot lines missing are a regression.

Looking at [mosso listing](https://dahlia-lap-full-pr-261.herokuapp.com/listings/a0W0P00000H3hJsUAJ) you can see the difference 
here's mosso on full:
![image](https://user-images.githubusercontent.com/11825994/58907343-cb0e4c00-86c2-11e9-8ca9-03696f9bf59d.png)

vs this PR:
![image](https://user-images.githubusercontent.com/11825994/58907359-d792a480-86c2-11e9-867c-8d5ef2aa0350.png)

2019-06-04 20:46 UTC, LoganArnett commented
Weird, I will update with master and see what is going on

2019-06-04 21:35 UTC, LoganArnett commented
@akegan found the issue here and updated

2019-06-06 18:39 UTC, akegan commented
@LoganArnett one last request, can you update the fixture that we have so that the open house info is correctly displayed in snapshot? looks like after latest change there's no test update so no test coverage for the open house info

2019-06-07 17:04 UTC, akegan approved these changes
Looks good to merge! 👍

2019-06-07 17:13 UTC, merged