Validate lease and rental assistances on save [DAH-93]
SFDigitalServices/sf-dahlia-lap pull request #405
Opened 2020-09-15 00:16 UTC by james-wills-sf

This adds lease and rental assistance validation on lease save.

I think opening the rental assistance panel on error is going to be difficult and probably not worth the work, but we can open a ticket to add it later. Especially now that rental assistances are properly validated it shouldn't be possible to save an assistance without a type

![save lease validation](https://user-images.githubusercontent.com/64036574/93150419-e92c6f80-f6ad-11ea-820f-dd9a1949a422.gif)

2020-09-15 17:27 UTC, akegan requested changes
Found an issue:

Steps to reproduce:
1. Create a rental assistance without type of assistance
1. Try to submit lease, see error above
1. Fix error by adding a type of assistance
1. Try saving lease again

It doesn't save but doesn't show an error. Saving the rental assistance individually works, but the lease still thinks there's an error I think.

I'm also wondering if we can add an alert bar or focus on the errored field or something. It is likely out of the scope of this pr, but it seems doable [with this library](https://github.com/final-form/final-form-focus) and right now it's a bit confusing because for me the errored field wasn't on the screen when I hit save so it wasn't clear at all why the button wasn't working.

2020-09-16 18:31 UTC, james-wills-sf commented
@akegan I'm actually not able to reproduce with this application: /applications/a0o0P00000JQawYQAT/supplementals

is it possible the application you're on has a different rental assistance with an invalid type?

Here's a gif in case I'm reproing it wrong:
![save working properly 2](https://user-images.githubusercontent.com/64036574/93377338-bbf7d280-f80f-11ea-89ec-80955366c2de.gif)

2020-09-16 21:25 UTC, akegan commented
@james-wills-sf I really thought that I tried also starting a new rental assistance and having the type set on the same application and saved by lease save and that was fine. I'll look again

2020-09-16 23:27 UTC, james-wills-sf commented
@akegan okay I fixed that specific error and fixed a small bug where clicking the top level page "save" button caused the edit forms to collapse when they shouldn't

Can you see if you're able to repro now?

2020-09-17 17:07 UTC, akegan approved these changes
looks good now! I had noticed that the rental assistance was collapsing kind of fast when I hit save so the 2nd fix with removing the submitting is great! All coming together 😄

2020-09-17 17:18 UTC, merged