Chores/application edit fields update #158821830
SFDigitalServices/sf-dahlia-lap pull request #43
Opened 2018-07-05 13:56 UTC by fddayan

https://www.pivotaltracker.com/story/show/158821830

2018-07-12 03:47 UTC, chrisdolendo commented
@fddayan did you do a q-a test on the review app for this chore? I'm getting an error when trying to open the applications page:

`NoMethodError (undefined method `parse_results_for_fields' for #<Force::ApplicationService:0x000000027047f0>):`

2018-07-12 03:47 UTC, chrisdolendo requested changes
cannot open applications page on review app :(

2018-07-12 12:13 UTC, fddayan commented
@chrisdolendo I merged with master, maybe something got broken let me check

2018-07-12 15:24 UTC, fddayan commented
@chrisdolendo you can test now. Fixed merging problems

2018-07-16 05:01 UTC, chrisdolendo commented
@fddayan 
The following are error-ing :( 
https://dahlia-lap-full-pr-43.herokuapp.com/listings/lease_ups/a0W0P00000DZfSpUAL/applications
https://dahlia-lap-full-pr-43.herokuapp.com/listings/a0W0P00000F8YG4UAN

Can you check on this again and do a smoke test on the features of the app before re-review?

2018-07-16 18:17 UTC, fddayan commented
@chrisdolendo ready

2018-07-18 19:06 UTC, callaghanc commented on app/javascript/components/applications/applicationsPageMapper.js
> +// import { map } from 'lodash'
@fddayan what is the purpose of this commented out file?

2018-07-18 19:07 UTC, callaghanc commented on spec/javascript/components/applications/application_form/PaperApplicationForm.test.js.old
> +// import React from 'react'
@fddayan what is the purpose of this commented out file?

2018-07-24 22:50 UTC, chrisdolendo approved these changes
After several reviews and re-reviews, this PR is ready to go! :+1: YAY!

2018-07-24 22:50 UTC, merged