Add waitlist and assigned numer to parking
SFDigitalServices/sf-dahlia-lap pull request #436
Opened 2020-10-22 18:28 UTC by software-project

Resolves: https://sfgovdt.jira.com/browse/DAH-146

2020-10-22 21:02 UTC, akegan requested changes
Couple of issues

Right now if you choose yes, then fill out values for cost + parking space number, then switch to "waitlist" or "no" the cost field clears out but the parking space field doesn't
![image](https://user-images.githubusercontent.com/11825994/96929444-21328980-1488-11eb-91c3-cb0d1b70c45f.png)

I think Chris also had a slightly different vision for how the fields should be lined up:
![image](https://user-images.githubusercontent.com/11825994/96929518-3f988500-1488-11eb-82ee-74ddf361a67b.png)

If it's feasible, I think we also wanted to hide the fields for cost + parking space number unless they choose "yes" instead of just disabling the fields.

2020-10-22 21:02 UTC, akegan commented on app/javascript/components/molecules/FormGrid.js
> +      { 'small-6': !(small || fullWidth || medium) },
I'm wondering if we can turn all 3 of these options into one option with proptypes setting the available options as ['small', 'medium', 'fullWidth'] or something like that. I also can't remember what the fullWidth option really does, but here you could set small + medium =true, then what would happen?

2020-10-22 21:19 UTC, james-wills-sf reviewed
only the one comment, i see andrea has comments on qa as well

2020-10-22 21:19 UTC, james-wills-sf commented on app/javascript/components/molecules/FormGrid.js
> +FormGrid.Item = ({ children, small = false, fullWidth = false, medium = false }) => (
We should convert these conflicting booleans into a single string enum

2020-10-23 16:57 UTC, akegan requested changes
One minor comment and 2 more QA issues:

1. We need to update the label + placeholder text to match the mock-up that chris made:
![image](https://user-images.githubusercontent.com/11825994/97032016-1f6fd100-152f-11eb-880a-4c4641097db4.png)
1. If it's feasible, we should hide the parking cost and the parking space fields unless "BMR parking space assigned" is "Yes", similar to how we disable it now.

2020-10-23 16:57 UTC, akegan commented on app/javascript/components/molecules/FormGrid.js
> +FormGrid.Item = ({ children, width }) => {
can you add proptypes to this component that lists out what the options are? here's an example where we specify which values are supported https://github.com/SFDigitalServices/sf-dahlia-lap/blob/main/app/javascript/components/atoms/Button.js#L20

2020-10-23 18:31 UTC, james-wills-sf commented
@akegan @software-project I can go ahead and make these changes and get this merged today

2020-10-23 19:56 UTC, james-wills-sf commented
@akegan this should be ready for another review. I addressed the comments you had and added a test for the parking inputs file

## When parking = yes
![- 2020-10-23 at 12 55 13 PM](https://user-images.githubusercontent.com/64036574/97048349-226ac180-152f-11eb-8af3-fbdc9b9f8ce3.png)

## When parking = no
![- 2020-10-23 at 12 55 18 PM](https://user-images.githubusercontent.com/64036574/97048353-239bee80-152f-11eb-9565-f60e3c8bad0b.png)

2020-10-23 21:07 UTC, akegan approved these changes

2020-10-23 21:07 UTC, akegan commented
looks good to merge! not sure why e2e tests have been so flaky lately. Just kicked them off again...

2020-10-23 21:34 UTC, merged