[LAP] Setup basic testing framework for the stack #156934719
SFDigitalServices/sf-dahlia-lap pull request #7
Opened 2018-04-20 22:57 UTC by fddayan

[#156934719]

2018-04-21 17:43 UTC, chrisdolendo commented
@fddayan could you update the readme and put instructions on how to run the tests?

2018-04-21 18:55 UTC, chrisdolendo requested changes
Looks awesome! Liking the snapshots. Please update Readme on how to run tests.

2018-04-23 13:31 UTC, fddayan commented
@chrisdolendo README updated

2018-04-23 15:19 UTC, chrisdolendo approved these changes

2018-04-24 04:45 UTC, merged